name: room_ranger
description: "Свободные даты для бронирования"
publish_to: 'none'
version: 0.8.0+113

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  package_info_plus: ^8.0.2
  http: ^1.1.0
  icalendar_parser: ^2.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home.png
    - assets/data/
    - .env
